# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Mon Jan  2 14:32:04 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(741, 472)
        self.centralWidget = QtGui.QWidget(MainWin)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainPanel = QtGui.QTabWidget(self.centralWidget)
        self.MainPanel.setObjectName("MainPanel")
        self.Config = QtGui.QWidget()
        self.Config.setObjectName("Config")
        self.gridLayout_2 = QtGui.QGridLayout(self.Config)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbUpdate = QtGui.QPushButton(self.Config)
        self.pbUpdate.setObjectName("pbUpdate")
        self.gridLayout_2.addWidget(self.pbUpdate, 0, 0, 1, 1)
        self.labelBook = QtGui.QLabel(self.Config)
        self.labelBook.setObjectName("labelBook")
        self.gridLayout_2.addWidget(self.labelBook, 1, 0, 1, 1)
        self.comboBookBox = QtGui.QComboBox(self.Config)
        self.comboBookBox.setObjectName("comboBookBox")
        self.gridLayout_2.addWidget(self.comboBookBox, 1, 1, 1, 1)
        self.labelGrid = QtGui.QLabel(self.Config)
        self.labelGrid.setObjectName("labelGrid")
        self.gridLayout_2.addWidget(self.labelGrid, 2, 0, 1, 1)
        self.comboGridBox = QtGui.QComboBox(self.Config)
        self.comboGridBox.setObjectName("comboGridBox")
        self.gridLayout_2.addWidget(self.comboGridBox, 2, 1, 1, 1)
        self.labelOutput = QtGui.QLabel(self.Config)
        self.labelOutput.setObjectName("labelOutput")
        self.gridLayout_2.addWidget(self.labelOutput, 3, 0, 1, 1)
        self.outputDirLine = QtGui.QLineEdit(self.Config)
        self.outputDirLine.setObjectName("outputDirLine")
        self.gridLayout_2.addWidget(self.outputDirLine, 3, 1, 1, 1)
        self.pb1Browse = QtGui.QPushButton(self.Config)
        self.pb1Browse.setObjectName("pb1Browse")
        self.gridLayout_2.addWidget(self.pb1Browse, 3, 2, 1, 1)
        self.pbGenerate = QtGui.QPushButton(self.Config)
        self.pbGenerate.setObjectName("pbGenerate")
        self.gridLayout_2.addWidget(self.pbGenerate, 4, 0, 1, 1)
        self.pbImport = QtGui.QPushButton(self.Config)
        self.pbImport.setObjectName("pbImport")
        self.gridLayout_2.addWidget(self.pbImport, 4, 2, 1, 1)
        self.MainPanel.addTab(self.Config, "")
        self.Distrib = QtGui.QWidget()
        self.Distrib.setObjectName("Distrib")
        self.pbGenerateOdds = QtGui.QPushButton(self.Distrib)
        self.pbGenerateOdds.setGeometry(QtCore.QRect(10, 300, 99, 22))
        self.pbGenerateOdds.setObjectName("pbGenerateOdds")
        self.MainPanel.addTab(self.Distrib, "")
        self.Odds = QtGui.QWidget()
        self.Odds.setObjectName("Odds")
        self.pbGenerateGrid = QtGui.QPushButton(self.Odds)
        self.pbGenerateGrid.setGeometry(QtCore.QRect(9, 159, 93, 22))
        self.pbGenerateGrid.setObjectName("pbGenerateGrid")
        self.MainPanel.addTab(self.Odds, "")
        self.gridLayout.addWidget(self.MainPanel, 0, 0, 1, 2)
        self.pbQuit = QtGui.QPushButton(self.centralWidget)
        self.pbQuit.setObjectName("pbQuit")
        self.gridLayout.addWidget(self.pbQuit, 1, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 1, 1, 1)
        MainWin.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 741, 19))
        self.menuBar.setObjectName("menuBar")
        MainWin.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWin)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWin)
        self.statusBar.setObjectName("statusBar")
        MainWin.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWin)
        self.toolBar.setObjectName("toolBar")
        MainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWin)
        self.MainPanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        MainWin.setWindowTitle(QtGui.QApplication.translate("MainWin", "MainWin", None, QtGui.QApplication.UnicodeUTF8))
        self.pbUpdate.setText(QtGui.QApplication.translate("MainWin", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBook.setText(QtGui.QApplication.translate("MainWin", "Book :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGrid.setText(QtGui.QApplication.translate("MainWin", "Grid :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutput.setText(QtGui.QApplication.translate("MainWin", "Output dir :", None, QtGui.QApplication.UnicodeUTF8))
        self.pb1Browse.setText(QtGui.QApplication.translate("MainWin", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGenerate.setText(QtGui.QApplication.translate("MainWin", "Generate distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImport.setText(QtGui.QApplication.translate("MainWin", "Import input file", None, QtGui.QApplication.UnicodeUTF8))
        self.MainPanel.setTabText(self.MainPanel.indexOf(self.Config), QtGui.QApplication.translate("MainWin", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGenerateOdds.setText(QtGui.QApplication.translate("MainWin", "Generate Odds", None, QtGui.QApplication.UnicodeUTF8))
        self.MainPanel.setTabText(self.MainPanel.indexOf(self.Distrib), QtGui.QApplication.translate("MainWin", "Distrib", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGenerateGrid.setText(QtGui.QApplication.translate("MainWin", "Generate Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.MainPanel.setTabText(self.MainPanel.indexOf(self.Odds), QtGui.QApplication.translate("MainWin", "Odds", None, QtGui.QApplication.UnicodeUTF8))
        self.pbQuit.setText(QtGui.QApplication.translate("MainWin", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWin", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

